[Variables]
;########################
;  Observal Drive Letter
;########################
; Write the observal target drive letter WITHOUT ":".
Drive1st = C
Drive2nd = F
Drive3rd = G
Drive4th = Q

;########################
;  AudioPlayer
;########################
; UnComment Your Audio Player
;-- AIMP --
;PlayerName = AIMP

;-- foobar2000, J.River Media Center, Jedia Jukebox, MusicBee --
;PlayerName = CAD

;-- iTunes --
PlayerName = iTunes

;-- MediaMonkey --
;PlayerName = MediaMonkey

;-- Winamp --
;PlayerName = Winamp

;-- WMP --
;PlayerName = WMP

;########################
;#  Weather
;########################
;-- Unit Of Measurement Code (m = celcius / f = fahrenheit)
UnitCode = m

;-- Location Code of Weather.com
LocationCode = JAXX1644

;-- Location Code of tenki.jp
PrefectureCode = 12

;-- Display Language --
Locale = en_us